<a href="https://colab.research.google.com/github/anyoonee/ai/blob/%2Bphython/6%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install numpy;
! pip install pandas;

In [ ]:
# 배열생성
import numpy as np;

# 리스트를 생성하고 배열로 변환하기
list1 = [1,2,3,4]
a = np.array(list1)
print('a.shape:',a.shape)
print('a[0]:',a[0])

# 2차원 배열생성하기
b = np.array([[1,2,3],[4,5,6]])
print('b.shape:', b.shape)
print('b[0,0]:', b[0,0])
print('b[0]:',b[0])

a.shape: (4,)
a[0]: 1
b.shape: (2, 3)
b[0,0]: 1
b[0]: [1 2 3]


In [ ]:
# 배열생성 함수
# 실수형 배열 생성하기
a= np.array([1,2], dtype=np.float64)
print(a.dtype)

#정수형 배열로 변환하기
a_i8 = a.astype(np.int8)
print(a_i8.dtype)

float64
int8


In [ ]:
# 배열 속성 호출
arr = np.array([[0,1,2],[3,4,5]])

print('type(arr):', type(arr))
print('arr.ndim:', arr.ndim)
print('arr.dtype:', arr.dtype)
print('arr.itemsize:', arr.itemsize)
print('arr.size:', arr.size)
print('arr.nbytes:', arr.nbytes)
print('arr.T:\n', arr.T)
print('arr.shape:', arr.shape)

type(arr): <class 'numpy.ndarray'>
arr.ndim: 2
arr.dtype: int64
arr.itemsize: 8
arr.size: 6
arr.nbytes: 48
arr.T:
 [[0 3]
 [1 4]
 [2 5]]
arr.shape: (2, 3)


In [ ]:
# 배열 모양 변경
#1차원 배열 생성
a=np.arange(8)
print('a\n', a)

#다차원 배열로 변경
a.shape=(2,4)
print('shape\n', a.flatten())

#resize 함수로 모양 변경
a.resize((4,2))
print('resize\n',a)

In [ ]:
# 행렬의 행과 열 교차
a = np.array([[0,1,2],[3,4,5]])
print('a\n', a)

b= a.transpose()
print('b\n',b)

c=a.T
print('c\n',c)

In [ ]:
# reshaping
b = np.arange(12) # 1차원 벡터 생성
print(b)
b.shape
#b.shape = 2,-1 # 요소의 갯수가 안맞으니까 오류

print(b)
b.shape
b.shape = 3,-1
print(b)
b.shape
b.shape=-1,1
print(b)
b.shape
b.shape=-1,3
print(b)
b.shape
b.shape=-1
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


- 자료형
  - int형 (정수)
   - int64,int16,int8, unit64
   - -2^63 ~ 2^62 -1 범위의 정수를 표현할 수 있다.
   - -2^15 ~ 2^15-1
   - 0 ~ 2^127 unit64의 정수표현의 범위 양의정수만 구한다.

  - float형 (실수)
   - float64, float32, float16
   - 자료저장 모습: 부호비트1비트     지수부7비트  가수부(8 or 24 or 58)
   - 소수점 아래를 저장하는 공간이 많아지게 하는 것
   - 실수의 기본은 float64이다.

  - complex형 (복소수)
   - complex128, complex64

In [ ]:
# int 32의 자료표현의 범위 -2147483648 ~ 2147483647까지 정수표현의 범위
a=np.array([1,3,5,7,9],np.int8) # 8비트 -2^7~ + 2^7
print(a)
a.dtype
a1 = np.array([2147483646, 2147483647, 2147483649], np.int64)
print(a1)
a2 = np.array([2**63, 2**63+1, 2**63+2], np.uint64)
print(a2)
a2.dtype
a3=np.array([2**62, -2**62])
print(a3)
a3.dtype
a4 = np.array([1,3,5,7,9]) # 64비트로 처리
print(a4)
a4.dtype

[1 3 5 7 9]
[2147483646 2147483647 2147483649]
[9223372036854775808 9223372036854775809 9223372036854775810]
[ 4611686018427387904 -4611686018427387904]
[1 3 5 7 9]


dtype('int64')

In [ ]:
# 실수형
a = np.array(3.141592653589793, np.float16)
print(a)
a.dtype
a2 = np.array(3.14)
print(a2)
a2.dtype

3.14
3.14


dtype('float64')

In [ ]:
# 복소수
a= np.array([1,2j, 3+4j, 2.72+3.14j])
print(a)
a.dtype
a.real # 실수만 추출
a.imag # 허수만 추출
print(a.real.dtype, '!!')
print(a.imag.dtype,'~~')

[1.  +0.j   0.  +2.j   3.  +4.j   2.72+3.14j]


array([0.  , 2.  , 4.  , 3.14])

1.인덱싱 indexing 1) 1DArray 2) 2DArray
2.슬라이싱 slicing 1) 1DArray 2) 2DArray
3. iterating 1) 1DArray 2) 2DArray

In [ ]:
# 인덱싱 indexing 1) 1DArray 2) 2DArray
a=np.array([1,3,5,7,9])
print(a)
print(a.ndim)
print(a.shape)
print(a[0])
print(a[3])
print(a[4])
print(a[-1])
print(a[-2])

[1 3 5 7 9]
1
(5,)
1
7
9
9
7


In [ ]:
# 인덱싱 indexing 2)2DArray
a2 = np([1,3,5],[2,4,6])
print(a2)
print(a2.ndim)
print(a2.shape)
# 1,5,4 추출하기
print(a2[0,0],a2[0,2],a2[1,1])
#6,3
print(a2[1,2],a2[0,1])
#3값을 13으로
a2[0,1]=13
#2값을 25로
a2[1,0]=25
print(a2)
#0번행 전체의 값에다 +10
print(a2[0])
print(a2[0,:])
print(a2[0,0:3])
a2[0] = a2[0] + 10
print(a2[0])
#1번행에 2곱하기
a[1] = a[1] *2
#1번열에 2곱하기
a2[:,1:2] = a2[:, 1:2] /2
print(a2)


In [ ]:
# 슬라이싱 slicing 1) 1DArray 2) 2DArray
print(a.shape)
print(a[0,])
print(a[1:])
print(a[2:])
print(a[3:])
print(a[:0]) #[]
print(a[:1])
print(a[:2])
print(a[:-1])
pirnt(a[:-2])
print(a[1:4]) # 357

a2=np.arange(10) # 0~9까지 연속적인 수의 배열만들기
print(a2)
print(a2[::2]) # 처음 인덱스(포함): 끝인덱스(미포함):증가인덱스 증가가+1,-1이면 생략 [0 2 4 6 8]
print(a2[::3]) # [0 3 6 9]
print(a2[::-1])
print(a2[::-2])
print(a2[1::2])
print(a2[:-2:2])
print(a2[:-4:2]) # [0,2,4]
print(a2[2:-2:2])#[2,4,6]

a3=np.arange(15)
# 1,3,5,7,9 출력
print(a3[1:10:2])
# 2,4,6,8,10,12 출력
print(a3[2:13:2])
# 14,13,12,11,10출력
print(a3[-1:9:-1])
# 전부다 출력
print(a3[::])
# 1열 전부 출력
print(a3[1:2])
# 마지막 열 출력
print(a3[-1:-2:-1])


In [ ]:
# 슬라이싱 slicing 2D Array
a=np.arange(10,25).reshape(3,5)
print(a)
print(a.ndim)
print(a.shape)
print(a[:])
print(a[0:])
print(a[1:]) # 1행부터 끝행까지
print(a[-1:]) # 제일 마지막행
print(a[-2:])
print(a[-3:])
print(a[:0])
print(a[:1])  # 0행
print(a[:-1]) # 0행 1행
print(a[:,2:])
print(a[:,-3:])

a=np.arange(10,25).reshape(3,5)
# 10~100까지 9X10 2차원 배열
a=np.arange(10,100).reshape(9,10)
print(a)





[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
2
(3, 5)
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
# iterating - 반복자 1) 1DArray 2) 2DArray
a = np.arange(11) ** 3
print(a)
for a1 in a:
  print(a1)

[   0    1    8   27   64  125  216  343  512  729 1000]
0
1
8
27
64
125
216
343
512
729
1000


In [ ]:
# concatenate
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b)) # a,b 배열을 행으로 합치기
print(c)

print(c)

In [ ]:
# concatenate 2d
a=np.array( [ [1,2],[3,4]  ]    )
b=np.array( [ [5,6],[7,8]  ]    )
print(a)
print(b)
c = np.concatenate( (a,b), axis=0 ) #행으로 합치기
print( c )
c = np.concatenate( (a,b), axis=1 ) # 열로 합치기
print( c )

c = np.r_[ a, b] #행으로 합치기
print(c )
c=np.c_[a, b] # 열로 합치기
print( c )

In [ ]:
# hstack-수평, vstack-수직
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c = np.hstack((a,b)) # (튜플){딕셔너리}{list}
print(c)
c1 = np.vstack((a,b))
print(c1)

In [ ]:

a=np.zeros(5) # 5열 전체에 0으로 채우기
print(a)
a=np.ones(5) # 5열 전체에 1로 채우기
print(a)
a2 = np.zeros( (3,5) ) # 3행 5열
print( a2 )
# 5X4 1
a3 = np.ones( (5, 4 )  )
print( a3 )
print( a.dtype )
print( a.ndim )
# 모든 요소값을 전부 5로 하고 싶다
a=np.full( 10, 5) # 10열 5값을 전부 넣기
print( a )
# 3행 4열에 모든 값일 7로 넣고 싶다
c = np.full( (3,4), 7 )
print( c )

In [ ]:
#empty 항목을 초기화 하지 않고 주어진 모양과 유형의 새 배열을 반환
a = np.empty(4)
print( a )
a = np.empty(4, dtype=np.int64)
print( a )
a = np.empty( (2,4), dtype=np.int32 )
print( a )

In [ ]:
# 행렬 곱하기
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,2],[3,3],[4,4]])
c = a@b
print(c)
c=np.matmul(a,b)
print(c)

[[20 20]
 [47 47]]
[[20 20]
 [47 47]]


In [ ]:
# 제곱
a = np.array([1,2,3,4])
a1 = np.square(a) # 제곱
print(a1)

#제곱근
a = np.array([1,2,3,4])
print(np.a)

In [ ]:
import numpy as np
np.exp(1)
x = np.array([0,1,2])
y = np.exp(x)
print(y)

[1.         2.71828183 7.3890561 ]


In [ ]:
import matplotlib.pyplot as plt # 그래프 그리기
x = np.linespace(-2,2,100)
y = np.exp(X)
# print(y)
plt.plot(y)


random - 난수
rand

In [ ]:
np.random.rand() # 1개 랜덤수
print(np.random.rand(3)) # 3열짜리 랜덤수
print(np.random.rand(3,5)) # 3행5열짜리 랜덤수 구하기


array([0.28545137, 0.48185902, 0.1881358 ])



> 파일로 저장하기 np.save('파일명',넌파이자료)


파일로 불러오기 변수 = np.load('파일명')

In [ ]:
# 0~99까지 10행 10열 2차원 배열만들기
a = np.arange(0,100).reshape(10,10)
print(a)
np.save('test.npy')


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


TypeError: save() missing 1 required positional argument: 'arr'

In [ ]:
# 넌파이 불러오기
k = np.load('test.npy')
print(k)


FileNotFoundError: [Errno 2] No such file or directory: 'test.npy'

In [ ]:
import numpy as np
from google.colab import files
f = files.upload() # 파일업로드하기
data = np.loadtxt('chocolate_rating.csv',delimiter=',')

Saving chocolate_rating.csv to chocolate_rating (1).csv


In [ ]:
# print(data)
print(data.ndim)
print(data.shape)
print(data.size)

2
(1795, 4)
7180


In [ ]:
rating_mean = data[:,3].mean()
# print(rating_mean)

high_level = data[data[:,3]>=4]
#print(high_level[0:10])
high_id = high_level[:,0].astype(np.int64)
print(high_id)



[  10   18   21   55   57   77   78   79   84   87   88   93  108  109
  118  124  153  180  181  187  223  232  233  240  243  244  245  248
  257  312  316  317  358  437  503  567  573  574  582  601  650  687
  690  691  701  720  730  800  828  862  864  865  866  883  919  993
 1088 1089 1118 1119 1120 1204 1241 1245 1247 1274 1277 1278 1289 1291
 1293 1295 1323 1331 1336 1378 1394 1426 1428 1433 1479 1488 1513 1516
 1529 1530 1531 1533 1536 1537 1544 1545 1664 1683 1686 1688 1694 1700
 1740 1757]


In [ ]:
high_kakao = high_level[:,2]
print(high_kakao)
unique_values, value_counts = np.unique(high_kakao, return_counts=True)
print('카카오함유량',unique_values)

[0.7  0.7  0.63 0.7  0.7  0.7  0.75 0.7  0.7  0.7  0.66 0.6  0.7  0.7
 0.7  0.72 0.7  0.73 0.72 0.72 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75
 0.7  0.71 0.7  0.7  0.72 0.75 0.7  0.7  0.7  0.7  0.7  0.7  0.68 0.7
 0.74 0.69 0.7  0.74 0.7  0.72 0.7  0.74 0.7  0.72 0.72 0.7  0.7  0.63
 0.68 0.74 0.67 0.65 0.64 0.75 0.7  0.7  0.7  0.75 0.7  0.67 0.7  0.72
 0.72 0.72 0.75 0.75 0.8  0.75 0.75 0.7  0.78 0.65 0.7  0.72 0.7  0.75
 0.88 0.7  0.67 0.7  0.7  0.7  0.64 0.7  0.7  0.63 0.69 0.64 0.64 0.7
 0.7  0.7 ]
[0.6  0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75
 0.78 0.8  0.88]


In [ ]:
max = np.max(value_counts)
print(max)

45


넌파이 복습 문제

1. 넘파이 모듈을 np라는 이름으로 임포트해보세요.

In [ ]:
import numpy as np

 2. 리스트를 넘파이의 ndarry 객체로 변환해보세요. data = [1,2,3]

In [ ]:
data = [1,2,3]
a = np.array(data)
print('a.shape:',a.shape)
print('a[0]:',a[0])

3. 0부터 99까지의 정수가 저장된 ndarray 객체를 만들어 보세요( 힌트 arange)

In [ ]:
ndarray = np.arange(100)
print('3'), ndarray

4. 구구단 3단의 결과가 저장된 gugu객체를 만들어 보세요 ( 힌트 arange)

    gugu [ 3 6 9 12 15 18 21 24 27]

In [ ]:
gugu = np.arange(1,10)*3
print('4',gugu)

5. 1000보다 작은 짝수가 저장된 evenObj 객체를 만드시오 ( 힌트 arange)

In [ ]:
evenObj = np.arange(2,1000,2)
print('5', evenObj)

6. 0부터 1까지 0.1간격으로 구성된 aObj 객체를 만드시오 1은 포함되지 않습니다

In [ ]:
aObj = np.arange(0,1,0.1)
print('6', aObj)

6 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


7. 리스트에는 6개의 데이터가 저장되 있습니다 data=[0,1,2,3,4,5]   
   다음과 같이 2행 3열의 a7객체로 변환하세요 [[0 1 2] [3 4 5 ] ]

In [ ]:
data =[0,1,2,3,4,5]
a7 = np.array(data).reshape(2,3)
print('7',a7)

7 [[0 1 2]
 [3 4 5]]


8. 힌트 reshape 다음의 2차원 a8 1차원 a81로 변환하세요   
   a8 = np.array( [ [0,1,2],[3,4,5] ] )

In [ ]:
a8 = np.array([ [0,1,2],[3,4,5] ])
a81 = a8.reshape(6)
print('8',a81)

8 [0 1 2 3 4 5]


9. 힌트 reshape 주어진 a9를 다음과 같이 변경해 보세요
a9 = np.arange(3) [ [0]  [1]  [2] ]

In [ ]:
a9 = np.arange(3)
a9 = a9.reshape( 3, 1)
print('9', a9)

IndexError: list index out of range

10. 아래 코드는 에러가 난다 이유는?
    np.arange(6).reshape(2,4)
    reshqpe(2,4)는 2행 4열로 8개의 원소필요
    arange(6)은 6개이므로 원소의 갯수가 맞지 않는다.

11. 다음과 같이 2차원 a11객체를 만드세요 [ [0 1 2]   [3 4 5 ] ]

In [ ]:
data = [ [0 ,1, 2] ,  [3 ,4, 5 ] ]
a11 = np.array(data)
print('11',all)

12. 1이 20개 저장된 아래의 a12객체를 만들어 보세요 (힌트 ones)
     [ 1 1 1 1 1 1 1 1 1  1 1 1 1 1 1  1 1]

In [ ]:
a12 = np.ones(20 , dtype=int)
print('12',a12)

13. 4행 5열로 저장된 아래의 a13객체를 만드시오
    [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

In [ ]:
a13 = np.ones(20, dtype=int).reshape(4,5)
print('13',a13)

14.  255로 채워진 10 X 10 크기의 a14 객체를 생성하시오

In [ ]:
a14 = np.ones(100, dtype=int).reshape(10,10)
a14 = a14 * 255

15. 3 X 4 크기의 0으로 채워진 배열을 생성하시오 (힌트 zeros)

In [ ]:
a15= np.zeros((3,4))
print('15',a15)

16. [ 1, 2, 3]을 np.int32 타입의 a16 배열로 생성하시오(힌트 dtype)

In [ ]:
data = [1,2,3]
a16 = np.array(data,dtype=np.int32)
print('16',a16)

17. 다음 배열의 데이터 타입을 확인해 보세요
    a17 = np.array([ 1, 2, 3] )

In [ ]:
a17 = np.array([ 1, 2, 3] )
print('17',a17.dtype)

17 int64


18.  다음 배열의 데이터 타입을 확인해 보세요
     a18 = np.array([ '1', '2', '3'] )

In [ ]:
a18 = np.array([ '1', '2', '3'] )
print('18',a18.dtype)

19. 다음 데이터를 np.int16 타입의 배열로 형변환해 보세요
    a19 = np.array([ 1, 2, 3] )

In [ ]:
a19 = np.array([ 1, 2, 3] )
print('19 기본자료형', a19.dtype)
a19 = a19.astype(np.int16)
print('19 형변환한 자료형 ',a19.detype)

20. 300이 44로 출력되는 이유를 설명하세요
    a = np.array( [ 255, 300, 128], dtype=np.uint8 )
    a
    [255  44 128]

    300은 자료표현의 범위에서 벗어남(넘침) 다른 값 출력

21. 힌트 astype
    a21배열은 float64 타입입니다. 이를 np.int32타입으로 변경하세요.
    import numpy as np
    a21=np.array([ 1.1, 2.1, 3.1 ])
    a21

In [ ]:
import numpy as np
a21 = np.array([ 1.1, 2.1, 3.1 ])
a21 = a21.astype(np.int32)
print('21',a21)
print('21 dtype', a21.dtype)

21 [1 2 3]
21 dtype int32


22. 0~10사이 구간을 20개의 포인터로 분할한 결과를 a22객체로 생성하시오(힌트 linespace)
  array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
          2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
          5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
          7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
a22 = np.linspace (0,10,20)
print('22',a21)

22 [1 2 3]


23.  아래 객체에서 마지막 행[6,7,8]을 출력해 보세요
    a23 = np.arange(9).reshape(3, 3)
    a23
  [[0 1 2] [3 4 5] [6 7 8]]


In [ ]:
a23 = np.arange(9).reshape(3, 3)
print('23', a23[-1])

24. 데이터 인덱싱
   아래 객체에서 마지막 17 출력해 보세요
  a24 = np.arange(25).reshape(5, 5)
  a24
  [[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

In [ ]:
a24 = np.arange(25).reshape(5, 5)
print('24',a24[3,2])

24 17


 25. 슬라이싱   [1 3]을 슬라이싱 하세요

In [ ]:
a25=np.arange(5)
print('25',a25[1::2]) # [시작: 끝 : 증가]


26. [ 6 7 8 9]를 슬라이싱 하는 코드를 작성하기

> a26 = np.arange(25).reshape(5, 5)

> a26

[[ 0  1  2  3  4]

 [ 5  6  7  8  9]

 [10 11 12 13 14]

 [15 16 17 18 19]

 [20 21 22 23 24]]


In [ ]:
a26 = np.arange(25).reshape(5, 5)
print('26',a26[1,1:])

27. 첫번째와 두번째 컬럼을 슬라이싱하는 코드 작성

> a27 = np.arange(25).reshape(5, 5)

> a27

[[ 0  1  2  3  4]

 [ 5  6  7  8  9]

 [10 11 12 13 14]

 [15 16 17 18 19]

 [20 21 22 23 24]]

In [ ]:
a27 = np.arange(25).reshape(5,5)
print('27',a27[:,:2])

28.  6. 7,11, 12 를 2x2 ndarray로 슬라이싱하는 코드를 작성하세요.

> a28 = np.arange(25).reshape(5, 5)

> a28

[[ 0  1  2  3  4]

 [ 5  6  7  8  9]

 [10 11 12 13 14]

 [15 16 17 18 19]

 [20 21 22 23 24]]

In [ ]:
a28 = np.arange(25).reshape(5,5)
print('28',a28[1:3,1:3])

29. 0 3 20 23 를 2x2 ndarray로 슬라이싱하는 코드를 작성하세요.
> a29 = np.arange(25).reshape(5, 5)

> a29

[[ 0 1 2 3 4]

[ 5 6 7 8 9]

[10 11 12 13 14]

[15 16 17 18 19]

[20 21 22 23 24]]

​

In [ ]:
a29 = np.arange(25).reshape(5, 5)
print('29-1',a29[0::4,0::3])
print('29', a29[[0,0,-1,-1],[0,3,0,3]]) # ([행1, 행2, 행3, 행4], [열1, 열2, 열3, 열4])

29-1 [[ 0  3]
 [20 23]]
29 [ 0  3 20 23]


30. 전체 데이터에 10을 곱한 결과를 a30에 저장하기

data=[1,2,3]​

In [ ]:
data=[1,2,3]
a30 = np.array(data)*10
print('30',a30)

30 [10 20 30]


31. 다음 a31에는 중간고사의 국어점수(10), 영어점수(20), 기말고사의 국어점수(14), 영어점수(16)이 저장되 있다

score = np.array([

    [10, 20],  # 중간고사

    [14, 16]   # 기말고사

])

​

과목별 평균점수를 출력하세요

결과 화면 [12. 18.]

In [ ]:
a31 = np.array([[10, 20],  [14, 16]  ])
print('31', a31.mean(axis=0))


31 [12. 18.]


32. 31번 문제에서 표준편차를 구하세요


In [ ]:
a31 = np.array([[10, 20],  [14, 16]  ])
print('32', a31.std(axis=0))

32 [2. 2.]


33. 행과 열의 위치를 바꾼 행열을 전치행렬이라고 한다.
a32 = np.arange(9).reshape(3,3)


In [ ]:
a33 = np.arange(9).reshape(3,3)
print('33-원래',a33)
print('33-전치행렬',a33.T)
print('33-전치행렬',a33.transpose())

34.  다음 배열에서 3보다 크고 7보다 작은 수만 출력하세요

a34 = np.arange(10)


In [ ]:
a34 = np.arange(10)
print('34',a34[(a34>3) & (a34<7)])

35. 다음 객체에서 음수를 출력하세요
a35 = np.array([ -1, 2, -3, 4] )​

In [ ]:
 a35 = np.array([ -1, 2, -3, 4] )
 print('35​',a35[(a35<0)])

35​ [-1 -3]


35. 다음 객체에서 음수를 0으로 바꾸세요
a35 = np.array([ -1, 2, -3, 4] )

In [ ]:
a35 = np.array([ -1, 2, -3, 4] )
a35[a35<0]=0
print('35',a35)

35 [0 2 0 4]


36.  다음 객체에서 음수를 양수로 바꾸세요

a36 = np.array([ -1, 2, -3, 4] )

In [ ]:
a36 = np.array([ -1, 2, -3, 4] )
#a36[a36<0]=a36[a36<0]*-1
print('36', np.abs(a36))
print('36',a36)

36 [1 2 3 4]
36 [-1  2 -3  4]


37. 다음 객체에서 양수 혹은 0이면 10을 더하고 음수는 10을 빼세요

a37 = np.array([ -1, 2, -3, 4] )

In [ ]:
a37 = np.array([ -1, 2, -3, 4] )
a37[a37>=0] = a37[a37>=0]+10
a37[a37<0] = a37[a37<0] -10
print('37', a37)

38. numpy random 모듈의 shuffle 함수를 사용해서 입력 리스트의 원소들을 랜덤하게 썩어 보세요

 a38 = [ 1,2,3,4,5]

In [ ]:
a38 = [ 1,2,3,4,5]
print('38',np.random.shuffle(a38))

38 None


39. 다음 넘파이 배열의 최소값의 인덱스를 출력하세요(힌트 argmin)

a39 = np.array([ 1,2,3,4,5] )

In [ ]:
a39 = np.array([1,2,3,4,5])
print('39', np.argmin(a39))

40. 다음 넘파이 배열의 최대값의 인덱스를 출력하세요(힌트 argmax)

a40 = np.array([ 1,2,3,4,5] )

In [ ]:
a40 = np.array([ 1,2,3,4,5] )
print('40', np.argmax(a40))

41. 넘파이 배열을 오름차순 정렬해 보세요

import numpy as np

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
import numpy as np

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print('41', np.sort(41))

42. numpy.vstack 함수를 사용하여 다음 2차원 배열을 생성하세요

arr1 = np.array([1, 2])

arr2 = np.array([3, 4])

결과화면

array([[1, 2],

       [3, 4]])

In [ ]:
arr1 = np.array([1, 2])

arr2 = np.array([3, 4])

a42 = np.vstack((arr1,arr2))

print('42',a42)

42 [[1 2]
 [3 4]]


43. flatten 메소드를 이용하여 다음 배열을 1차원 배열로 변경하세요
import numpy as np

arr = np.array([ [1, 2], [3, 4] ])

In [ ]:

import numpy as np

a43 = np.array([ [1, 2], [3, 4] ])
a43 = np.flatten(a43)
print('43', a43)

AttributeError: module 'numpy' has no attribute 'flatten'